baseURL = "https://agilesyndro.me/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "AgileSyndro.me"
theme = 'cupper-hugo-theme'
publishDir = "docs"
enableGitInfo = true
disqusShortname = "agilesyndrome"

[taxonomies]
	tag="tags"

[permalinks]
	post = "/:filename/"

[imaging]
	quality = 99

[params]
	author = "Drew E. Easley"
	description = "Empowering the Open Source"
	footer = "2019"
        heapSiteId = "1793759258"

[menu]
  [[menu.nav]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Blog"
    url = "/blog"
    weight = 20
  [[menu.nav]]
    name = "Projects"
    url = "/projects"
    weight = 30
  [[menu.nav]]
    name = "Contact"
    url = "/contact"
    weight = 40
  [[menu.nav]]
    name = "RSS"
    url = "/index.xml"
    weight = 50
